################################################
#
# BUNGEESTAFFS - v0.3
# https://discord.gg/gXzRaYdzsh
#
################################################

# Turn between bungeecord motd name or server name
# for variable <server>.
USE-BUNGEE-MOTD: true

# Language file selection.
LANGUAGE: en_US

# Disable primary command tab executor. Example: /report
DISABLE-PRIMARY-COMMAND-TAB: false

########################################################################################
# CUSTOM CHAT FORMATTER
# for our own custom message formatter.
#
# Available parameters:
#  - (show_text=<message>) - Text to show hover message.
#  - (run_command=<command>) - Run command when click.
#  - (suggest_command=<command>) - Suggest command when click.
#  - (format=<text_format>) - Available text format: underline, strikethrough, bold, italic
#  - (color=<hex code>) - Use new HEX color codes.
#  - (color=<hex code>-<hex code>) - Use new HEX color codes with gradient.
#
# Parameters can be added after ${} format.
# Example of custom message formatter:
#  - '&eClick ${&e&lHERE}(run_command=/server <server>)(show_text=&bClick here to join) &eto join server.'
#  - '&ePlayer is connected! Server: ${<server>}(run_command=/server <server>).'
########################################################################################

REDIS-INTEGRATION: false

DISCORD-INTEGRATION:
  ENABLED: false

  BOT-TOKEN: '<token>'

  UPDATE-DELAY: 5 # In seconds
  ACTIVITY: 'Players online: <bungee_online>'
  ACTIVITY-URL: 'play.example.net'
  ACTIVITY-TYPE: 'STREAMING' ## Available parameters: DEFAULT, STREAMING, LISTENING, WATCHING, COMPETING.

EVENTS:
  JOIN-UPDATE-MESSAGE: true

  LOGS:
    LOG-METHOD: 'CONSOLE' ## Available parameters: CONSOLE, FILE, BOTH.

    CHAT: true
    COMMANDS: true
    MOVE: true

  STAFFS:
    PERMISSION: 'bstaffs.staff'

    JOIN-MESSAGE: true
    LEFT-MESSAGE: true
    MOVE-MESSAGE: true

SERVERS-CONFIG:
  LIMBO:
    # The maximum time that the server can be restarted without giving a signal.
    TIMEOUT: 10
    # Countdown in seconds to teleport again to old server after server give a signal.
    TP-COOLDOWN: 15

    # Prevent player moving to other servers while in limbo.
    PREVENT-MOVE: false
    # Command who execute player to stop the server.
    STOP-COMMAND: '/stop'
    NAME: 'Limbo' # Limbo server name.

  # If message contains a words of below list, the player will not move to fallback server.
  KICK-MESSAGE-BLACKLIST:
    - 'cheating'

  # Fallback servers are server who you teleport to when the server where you are is offline.
  FALLBACK-SERVERS:
    - 'lobby1'
    - 'lobby2'