################################################
#
# BUNGEESTAFFS - v0.3
# https://discord.gg/gXzRaYdzsh
#
################################################

# Turn between bungeecord motd name or server name
# for variable <server>.
USE-BUNGEE-MOTD: true

EVENTS:
  STAFFS:
    PERMISSION: 'bstaffs.staff'

    JOIN-MESSAGE: true
    LEFT-MESSAGE: true
    MOVE-MESSAGE: true

SERVERS-CONFIG:
  LIMBO:
    PREVENT-MOVE: true
    STOP-COMMAND: '/stop'
    NAME: 'Limbo'

  FALLBACK-SERVERS:
    - 'lobby1'
    - 'lobby2'