################################################
#
# BUNGEESTAFFS - v0.3
# https://discord.gg/gXzRaYdzsh
#
################################################

# Turn between bungeecord motd name or server name
# for variable <server>.
USE-BUNGEE-MOTD: true

EVENTS:
  STAFFS:
    PERMISSION: 'bstaffs.staff'

    JOIN-MESSAGE: true
    LEFT-MESSAGE: true
    MOVE-MESSAGE: true